FROM node:20
RUN mkdir /app
WORKDIR /app
COPY ./ascent-essentials-frontend/package*.json ./
RUN npm install -g @angular/cli
RUN npm install
COPY ./ascent-essentials-frontend .
EXPOSE 4200
CMD ["ng", "serve", "--host", "0.0.0.0"]
