version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin # mongo admin username
      MONGO_INITDB_ROOT_PASSWORD: admin # mongo admin password
    ports:
      - 27017:27017

  mongo-dashboard:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081 # mongo bashboard port
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin # same mongo username as above
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin # same mongo password as above
      ME_CONFIG_BASICAUTH_USERNAME: test
      ME_CONFIG_BASICAUTH_PASSWORD: test
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  backend:
    depends_on:
          - mongo
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      MONGODB_URL: mongodb://admin:admin@mongo:27017/

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "4200:4200"
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: admin
      MONGO_HOST: mongo
      MONGO_PORT: 27017
